package py.pol.una.ii.pw.example;

import java.util.ArrayList;
import java.util.List;

public class DetallecompraExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public DetallecompraExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdCompraDetalleIsNull() {
            addCriterion("id_compra_detalle is null");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleIsNotNull() {
            addCriterion("id_compra_detalle is not null");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleEqualTo(Integer value) {
            addCriterion("id_compra_detalle =", value, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleNotEqualTo(Integer value) {
            addCriterion("id_compra_detalle <>", value, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleGreaterThan(Integer value) {
            addCriterion("id_compra_detalle >", value, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_compra_detalle >=", value, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleLessThan(Integer value) {
            addCriterion("id_compra_detalle <", value, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleLessThanOrEqualTo(Integer value) {
            addCriterion("id_compra_detalle <=", value, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleIn(List<Integer> values) {
            addCriterion("id_compra_detalle in", values, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleNotIn(List<Integer> values) {
            addCriterion("id_compra_detalle not in", values, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleBetween(Integer value1, Integer value2) {
            addCriterion("id_compra_detalle between", value1, value2, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraDetalleNotBetween(Integer value1, Integer value2) {
            addCriterion("id_compra_detalle not between", value1, value2, "idCompraDetalle");
            return (Criteria) this;
        }

        public Criteria andIdCompraIsNull() {
            addCriterion("id_compra is null");
            return (Criteria) this;
        }

        public Criteria andIdCompraIsNotNull() {
            addCriterion("id_compra is not null");
            return (Criteria) this;
        }

        public Criteria andIdCompraEqualTo(Integer value) {
            addCriterion("id_compra =", value, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdCompraNotEqualTo(Integer value) {
            addCriterion("id_compra <>", value, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdCompraGreaterThan(Integer value) {
            addCriterion("id_compra >", value, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdCompraGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_compra >=", value, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdCompraLessThan(Integer value) {
            addCriterion("id_compra <", value, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdCompraLessThanOrEqualTo(Integer value) {
            addCriterion("id_compra <=", value, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdCompraIn(List<Integer> values) {
            addCriterion("id_compra in", values, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdCompraNotIn(List<Integer> values) {
            addCriterion("id_compra not in", values, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdCompraBetween(Integer value1, Integer value2) {
            addCriterion("id_compra between", value1, value2, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdCompraNotBetween(Integer value1, Integer value2) {
            addCriterion("id_compra not between", value1, value2, "idCompra");
            return (Criteria) this;
        }

        public Criteria andIdProductoIsNull() {
            addCriterion("id_producto is null");
            return (Criteria) this;
        }

        public Criteria andIdProductoIsNotNull() {
            addCriterion("id_producto is not null");
            return (Criteria) this;
        }

        public Criteria andIdProductoEqualTo(Integer value) {
            addCriterion("id_producto =", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoNotEqualTo(Integer value) {
            addCriterion("id_producto <>", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoGreaterThan(Integer value) {
            addCriterion("id_producto >", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_producto >=", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoLessThan(Integer value) {
            addCriterion("id_producto <", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoLessThanOrEqualTo(Integer value) {
            addCriterion("id_producto <=", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoIn(List<Integer> values) {
            addCriterion("id_producto in", values, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoNotIn(List<Integer> values) {
            addCriterion("id_producto not in", values, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoBetween(Integer value1, Integer value2) {
            addCriterion("id_producto between", value1, value2, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoNotBetween(Integer value1, Integer value2) {
            addCriterion("id_producto not between", value1, value2, "idProducto");
            return (Criteria) this;
        }

        public Criteria andCantidadIsNull() {
            addCriterion("cantidad is null");
            return (Criteria) this;
        }

        public Criteria andCantidadIsNotNull() {
            addCriterion("cantidad is not null");
            return (Criteria) this;
        }

        public Criteria andCantidadEqualTo(Integer value) {
            addCriterion("cantidad =", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotEqualTo(Integer value) {
            addCriterion("cantidad <>", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadGreaterThan(Integer value) {
            addCriterion("cantidad >", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadGreaterThanOrEqualTo(Integer value) {
            addCriterion("cantidad >=", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadLessThan(Integer value) {
            addCriterion("cantidad <", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadLessThanOrEqualTo(Integer value) {
            addCriterion("cantidad <=", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadIn(List<Integer> values) {
            addCriterion("cantidad in", values, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotIn(List<Integer> values) {
            addCriterion("cantidad not in", values, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadBetween(Integer value1, Integer value2) {
            addCriterion("cantidad between", value1, value2, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotBetween(Integer value1, Integer value2) {
            addCriterion("cantidad not between", value1, value2, "cantidad");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.compra_detalle
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 23 22:10:07 PYT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}