package py.pol.una.ii.pw.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import py.pol.una.ii.pw.example.ClienteExample;
import py.pol.una.ii.pw.model.Cliente;
import py.pol.una.ii.pw.sqlprovider.ClienteSqlProvider;


public interface ClienteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @SelectProvider(type=ClienteSqlProvider.class, method="countByExample")
    int countByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @DeleteProvider(type=ClienteSqlProvider.class, method="deleteByExample")
    int deleteByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @Delete({
        "delete from cliente",
        "where id_cliente = #{idCliente,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idCliente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @Insert({
        "insert into cliente (id_cliente, ruc, ",
        "nombre, saldo)",
        "values (#{idCliente,jdbcType=INTEGER}, #{ruc,jdbcType=VARCHAR}, ",
        "#{nombre,jdbcType=VARCHAR}, #{saldo,jdbcType=INTEGER})"
    })
    int insert(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @InsertProvider(type=ClienteSqlProvider.class, method="insertSelective")
    int insertSelective(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @SelectProvider(type=ClienteSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ruc", property="ruc", jdbcType=JdbcType.VARCHAR),
        @Result(column="nombre", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="saldo", property="saldo", jdbcType=JdbcType.INTEGER)
    })
    List<Cliente> selectByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @Select({
        "select",
        "id_cliente, ruc, nombre, saldo",
        "from cliente",
        "where id_cliente = #{idCliente,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ruc", property="ruc", jdbcType=JdbcType.VARCHAR),
        @Result(column="nombre", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="saldo", property="saldo", jdbcType=JdbcType.INTEGER)
    })
    Cliente selectByPrimaryKey(Integer idCliente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @UpdateProvider(type=ClienteSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Cliente record, @Param("example") ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @UpdateProvider(type=ClienteSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Cliente record, @Param("example") ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @UpdateProvider(type=ClienteSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    @Update({
        "update cliente",
        "set ruc = #{ruc,jdbcType=VARCHAR},",
          "nombre = #{nombre,jdbcType=VARCHAR},",
          "saldo = #{saldo,jdbcType=INTEGER}",
        "where id_cliente = #{idCliente,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Cliente record);
}