package py.pol.una.ii.pw.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import py.pol.una.ii.pw.example.DetallecompraExample;
import py.pol.una.ii.pw.model.Detallecompra;
import py.pol.una.ii.pw.sqlprovider.DetallecompraSqlProvider;

public interface DetallecompraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=DetallecompraSqlProvider.class, method="countByExample")
    int countByExample(DetallecompraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @DeleteProvider(type=DetallecompraSqlProvider.class, method="deleteByExample")
    int deleteByExample(DetallecompraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Delete({
        "delete from detallecompra",
        "where id_compra_detalle = #{idCompraDetalle,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idCompraDetalle);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Insert({
        "insert into detallecompra (id_compra_detalle, id_compra, ",
        "id_producto, cantidad)",
        "values (#{idCompraDetalle,jdbcType=INTEGER}, #{idCompra,jdbcType=INTEGER}, ",
        "#{idProducto,jdbcType=INTEGER}, #{cantidad,jdbcType=INTEGER})"
    })
    int insert(Detallecompra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @InsertProvider(type=DetallecompraSqlProvider.class, method="insertSelective")
    int insertSelective(Detallecompra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=DetallecompraSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_compra_detalle", property="idCompraDetalle", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_compra", property="idCompra", jdbcType=JdbcType.INTEGER),
        @Result(column="id_producto", property="idProducto", jdbcType=JdbcType.INTEGER),
        @Result(column="cantidad", property="cantidad", jdbcType=JdbcType.INTEGER)
    })
    List<Detallecompra> selectByExample(DetallecompraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Select({
        "select",
        "id_compra_detalle, id_compra, id_producto, cantidad",
        "from detallecompra",
        "where id_compra_detalle = #{idCompraDetalle,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_compra_detalle", property="idCompraDetalle", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_compra", property="idCompra", jdbcType=JdbcType.INTEGER),
        @Result(column="id_producto", property="idProducto", jdbcType=JdbcType.INTEGER),
        @Result(column="cantidad", property="cantidad", jdbcType=JdbcType.INTEGER)
    })
    Detallecompra selectByPrimaryKey(Integer idCompraDetalle);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=DetallecompraSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Detallecompra record, @Param("example") DetallecompraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=DetallecompraSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Detallecompra record, @Param("example") DetallecompraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=DetallecompraSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Detallecompra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Update({
        "update detallecompra",
        "set id_compra = #{idCompra,jdbcType=INTEGER},",
          "id_producto = #{idProducto,jdbcType=INTEGER},",
          "cantidad = #{cantidad,jdbcType=INTEGER}",
        "where id_compra_detalle = #{idCompraDetalle,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Detallecompra record);
}