package py.pol.una.ii.pw.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import py.pol.una.ii.pw.example.PagoExample;
import py.pol.una.ii.pw.model.Pago;
import py.pol.una.ii.pw.sqlprovider.PagoSqlProvider;

public interface PagoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=PagoSqlProvider.class, method="countByExample")
    int countByExample(PagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @DeleteProvider(type=PagoSqlProvider.class, method="deleteByExample")
    int deleteByExample(PagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Delete({
        "delete from pago",
        "where id_pago = #{idPago,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idPago);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Insert({
        "insert into pago (id_pago, id_cliente, ",
        "fecha, pago)",
        "values (#{idPago,jdbcType=INTEGER}, #{idCliente,jdbcType=INTEGER}, ",
        "#{fecha,jdbcType=DATE}, #{pago,jdbcType=INTEGER})"
    })
    int insert(Pago record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @InsertProvider(type=PagoSqlProvider.class, method="insertSelective")
    int insertSelective(Pago record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=PagoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_pago", property="idPago", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER),
        @Result(column="fecha", property="fecha", jdbcType=JdbcType.DATE),
        @Result(column="pago", property="pago", jdbcType=JdbcType.INTEGER)
    })
    List<Pago> selectByExample(PagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Select({
        "select",
        "id_pago, id_cliente, fecha, pago",
        "from pago",
        "where id_pago = #{idPago,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_pago", property="idPago", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER),
        @Result(column="fecha", property="fecha", jdbcType=JdbcType.DATE),
        @Result(column="pago", property="pago", jdbcType=JdbcType.INTEGER)
    })
    Pago selectByPrimaryKey(Integer idPago);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=PagoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Pago record, @Param("example") PagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=PagoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Pago record, @Param("example") PagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=PagoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Pago record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Update({
        "update pago",
        "set id_cliente = #{idCliente,jdbcType=INTEGER},",
          "fecha = #{fecha,jdbcType=DATE},",
          "pago = #{pago,jdbcType=INTEGER}",
        "where id_pago = #{idPago,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Pago record);
}