package py.pol.una.ii.pw.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import py.pol.una.ii.pw.example.ProductoExample;
import py.pol.una.ii.pw.model.Producto;
import py.pol.una.ii.pw.sqlprovider.ProductoSqlProvider;

public interface ProductoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@SelectProvider(type = ProductoSqlProvider.class, method = "countByExample")
	int countByExample(ProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@DeleteProvider(type = ProductoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(ProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@Delete({ "delete from producto",
			"where id_producto = #{idProducto,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idProducto);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@Insert({
			"insert into producto (id_producto, nombre, ",
			"precio, stock)",
			"values (#{idProducto,jdbcType=INTEGER}, #{nombre,jdbcType=VARCHAR}, ",
			"#{precio,jdbcType=INTEGER}, #{stock,jdbcType=INTEGER})" })
	int insert(Producto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@InsertProvider(type = ProductoSqlProvider.class, method = "insertSelective")
	int insertSelective(Producto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@SelectProvider(type = ProductoSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id_producto", property = "idProducto", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "nombre", property = "nombre", jdbcType = JdbcType.VARCHAR),
			@Result(column = "precio", property = "precio", jdbcType = JdbcType.INTEGER),
			@Result(column = "stock", property = "stock", jdbcType = JdbcType.INTEGER) })
	List<Producto> selectByExample(ProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@Select({ "select", "id_producto, nombre, precio, stock", "from producto",
			"where id_producto = #{idProducto,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id_producto", property = "idProducto", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "nombre", property = "nombre", jdbcType = JdbcType.VARCHAR),
			@Result(column = "precio", property = "precio", jdbcType = JdbcType.INTEGER),
			@Result(column = "stock", property = "stock", jdbcType = JdbcType.INTEGER) })
	Producto selectByPrimaryKey(Integer idProducto);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@UpdateProvider(type = ProductoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Producto record,
			@Param("example") ProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@UpdateProvider(type = ProductoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Producto record,
			@Param("example") ProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@UpdateProvider(type = ProductoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Producto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	@Update({ "update producto", "set nombre = #{nombre,jdbcType=VARCHAR},",
			"precio = #{precio,jdbcType=INTEGER},",
			"stock = #{stock,jdbcType=INTEGER}",
			"where id_producto = #{idProducto,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Producto record);

	
}