package py.pol.una.ii.pw.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import py.pol.una.ii.pw.example.ProductoDuplicadoExample;
import py.pol.una.ii.pw.model.ProductoDuplicado;
import py.pol.una.ii.pw.sqlprovider.ProductoDuplicadoSqlProvider;

public interface ProductoDuplicadoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @SelectProvider(type=ProductoDuplicadoSqlProvider.class, method="countByExample")
    int countByExample(ProductoDuplicadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @DeleteProvider(type=ProductoDuplicadoSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProductoDuplicadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @Delete({
        "delete from producto_duplicado",
        "where id_producto_duplicado = #{idProductoDuplicado,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idProductoDuplicado);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @Insert({
        "insert into producto_duplicado (id_producto_duplicado, cantidad, ",
        "id_producto)",
        "values (#{idProductoDuplicado,jdbcType=INTEGER}, #{cantidad,jdbcType=INTEGER}, ",
        "#{idProducto,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys = true, keyProperty = "idProductoDuplicado")
    int insert(ProductoDuplicado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @InsertProvider(type=ProductoDuplicadoSqlProvider.class, method="insertSelective")
    int insertSelective(ProductoDuplicado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @SelectProvider(type=ProductoDuplicadoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_producto_duplicado", property="idProductoDuplicado", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="cantidad", property="cantidad", jdbcType=JdbcType.INTEGER),
        @Result(column="id_producto", property="idProducto", jdbcType=JdbcType.INTEGER)
    })
    List<ProductoDuplicado> selectByExample(ProductoDuplicadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @Select({
        "select",
        "id_producto_duplicado, cantidad, id_producto",
        "from producto_duplicado",
        "where id_producto_duplicado = #{idProducto,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_producto_duplicado", property="idProductoDuplicado", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="cantidad", property="cantidad", jdbcType=JdbcType.INTEGER),
        @Result(column="id_producto", property="idProducto", jdbcType=JdbcType.INTEGER)
    })
    ProductoDuplicado selectByPrimaryKey(Integer idProducto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @UpdateProvider(type=ProductoDuplicadoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ProductoDuplicado record, @Param("example") ProductoDuplicadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @UpdateProvider(type=ProductoDuplicadoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ProductoDuplicado record, @Param("example") ProductoDuplicadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @UpdateProvider(type=ProductoDuplicadoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ProductoDuplicado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    @Update({
        "update producto_duplicado",
        "set cantidad = #{cantidad,jdbcType=INTEGER},",
          "id_producto = #{idProducto,jdbcType=INTEGER}",
        "where id_producto_duplicado = #{idProductoDuplicado,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductoDuplicado record);
    
    @Select({
        "select",
        "id_producto_duplicado, cantidad, id_producto",
        "from producto_duplicado",
        "where id_producto = #{idProducto,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_producto_duplicado", property="idProductoDuplicado", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="cantidad", property="cantidad", jdbcType=JdbcType.INTEGER),
        @Result(column="id_producto", property="idProducto", jdbcType=JdbcType.INTEGER)
    })
    ProductoDuplicado selectByProductoDuplicado(Integer idProducto);
}