package py.pol.una.ii.pw.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import py.pol.una.ii.pw.example.ProveedorExample;
import py.pol.una.ii.pw.model.Proveedor;
import py.pol.una.ii.pw.sqlprovider.ProveedorSqlProvider;

public interface ProveedorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=ProveedorSqlProvider.class, method="countByExample")
    int countByExample(ProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @DeleteProvider(type=ProveedorSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Delete({
        "delete from proveedor",
        "where id_proveedor = #{idProveedor,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idProveedor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Insert({
        "insert into proveedor (id_proveedor, nombre)",
        "values (#{idProveedor,jdbcType=INTEGER}, #{nombre,jdbcType=VARCHAR})"
    })
    int insert(Proveedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @InsertProvider(type=ProveedorSqlProvider.class, method="insertSelective")
    int insertSelective(Proveedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=ProveedorSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_proveedor", property="idProveedor", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nombre", property="nombre", jdbcType=JdbcType.VARCHAR)
    })
    List<Proveedor> selectByExample(ProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Select({
        "select",
        "id_proveedor, nombre",
        "from proveedor",
        "where id_proveedor = #{idProveedor,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_proveedor", property="idProveedor", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nombre", property="nombre", jdbcType=JdbcType.VARCHAR)
    })
    Proveedor selectByPrimaryKey(Integer idProveedor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=ProveedorSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Proveedor record, @Param("example") ProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=ProveedorSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Proveedor record, @Param("example") ProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=ProveedorSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Proveedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Update({
        "update proveedor",
        "set nombre = #{nombre,jdbcType=VARCHAR}",
        "where id_proveedor = #{idProveedor,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Proveedor record);
}