package py.pol.una.ii.pw.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import py.pol.una.ii.pw.example.VentaDetalleExample;
import py.pol.una.ii.pw.model.VentaDetalle;
import py.pol.una.ii.pw.sqlprovider.VentaDetalleSqlProvider;

public interface VentaDetalleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=VentaDetalleSqlProvider.class, method="countByExample")
    int countByExample(VentaDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @DeleteProvider(type=VentaDetalleSqlProvider.class, method="deleteByExample")
    int deleteByExample(VentaDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Delete({
        "delete from venta_detalle",
        "where id_venta_detalle = #{idVentaDetalle,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idVentaDetalle);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Insert({
        "insert into venta_detalle (id_venta_detalle, id_venta, ",
        "id_producto, cantidad)",
        "values (#{idVentaDetalle,jdbcType=INTEGER}, #{idVenta,jdbcType=INTEGER}, ",
        "#{idProducto,jdbcType=INTEGER}, #{cantidad,jdbcType=INTEGER})"
    })
    int insert(VentaDetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @InsertProvider(type=VentaDetalleSqlProvider.class, method="insertSelective")
    int insertSelective(VentaDetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=VentaDetalleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_venta_detalle", property="idVentaDetalle", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_venta", property="idVenta", jdbcType=JdbcType.INTEGER),
        @Result(column="id_producto", property="idProducto", jdbcType=JdbcType.INTEGER),
        @Result(column="cantidad", property="cantidad", jdbcType=JdbcType.INTEGER)
    })
    List<VentaDetalle> selectByExample(VentaDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Select({
        "select",
        "id_venta_detalle, id_venta, id_producto, cantidad",
        "from venta_detalle",
        "where id_venta_detalle = #{idVentaDetalle,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_venta_detalle", property="idVentaDetalle", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_venta", property="idVenta", jdbcType=JdbcType.INTEGER),
        @Result(column="id_producto", property="idProducto", jdbcType=JdbcType.INTEGER),
        @Result(column="cantidad", property="cantidad", jdbcType=JdbcType.INTEGER)
    })
    VentaDetalle selectByPrimaryKey(Integer idVentaDetalle);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=VentaDetalleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") VentaDetalle record, @Param("example") VentaDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=VentaDetalleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") VentaDetalle record, @Param("example") VentaDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=VentaDetalleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(VentaDetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Update({
        "update venta_detalle",
        "set id_venta = #{idVenta,jdbcType=INTEGER},",
          "id_producto = #{idProducto,jdbcType=INTEGER},",
          "cantidad = #{cantidad,jdbcType=INTEGER}",
        "where id_venta_detalle = #{idVentaDetalle,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(VentaDetalle record);
}