package py.pol.una.ii.pw.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import py.pol.una.ii.pw.example.VentaExample;
import py.pol.una.ii.pw.model.Venta;
import py.pol.una.ii.pw.sqlprovider.VentaSqlProvider;

public interface VentaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=VentaSqlProvider.class, method="countByExample")
    int countByExample(VentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @DeleteProvider(type=VentaSqlProvider.class, method="deleteByExample")
    int deleteByExample(VentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Delete({
        "delete from venta",
        "where id_venta = #{idVenta,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idVenta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Insert({
        "insert into venta (id_venta, fecha, ",
        "id_cliente, monto)",
        "values (#{idVenta,jdbcType=INTEGER}, #{fecha,jdbcType=DATE}, ",
        "#{idCliente,jdbcType=INTEGER}, #{monto,jdbcType=INTEGER})"
    })
    int insert(Venta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @InsertProvider(type=VentaSqlProvider.class, method="insertSelective")
    int insertSelective(Venta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @SelectProvider(type=VentaSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_venta", property="idVenta", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="fecha", property="fecha", jdbcType=JdbcType.DATE),
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER),
        @Result(column="monto", property="monto", jdbcType=JdbcType.INTEGER)
    })
    List<Venta> selectByExample(VentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Select({
        "select",
        "id_venta, fecha, id_cliente, monto",
        "from venta",
        "where id_venta = #{idVenta,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_venta", property="idVenta", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="fecha", property="fecha", jdbcType=JdbcType.DATE),
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER),
        @Result(column="monto", property="monto", jdbcType=JdbcType.INTEGER)
    })
    Venta selectByPrimaryKey(Integer idVenta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=VentaSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Venta record, @Param("example") VentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=VentaSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Venta record, @Param("example") VentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @UpdateProvider(type=VentaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Venta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    @Update({
        "update venta",
        "set fecha = #{fecha,jdbcType=DATE},",
          "id_cliente = #{idCliente,jdbcType=INTEGER},",
          "monto = #{monto,jdbcType=INTEGER}",
        "where id_venta = #{idVenta,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Venta record);
}