package py.pol.una.ii.pw.sqlprovider;

import java.util.List;
import java.util.Map;

import py.pol.una.ii.pw.example.ClienteExample;
import py.pol.una.ii.pw.example.ClienteExample.Criteria;
import py.pol.una.ii.pw.example.ClienteExample.Criterion;
import py.pol.una.ii.pw.model.Cliente;
import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;


public class ClienteSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public String countByExample(ClienteExample example) {
    	
        BEGIN();
        SELECT("count(*)");
        FROM("cliente");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public String deleteByExample(ClienteExample example) {
        BEGIN();
        DELETE_FROM("cliente");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public String insertSelective(Cliente record) {
        BEGIN();
        INSERT_INTO("cliente");
        
        if (record.getIdCliente() != null) {
            VALUES("id_cliente", "#{idCliente,jdbcType=INTEGER}");
        }
        
        if (record.getRuc() != null) {
            VALUES("ruc", "#{ruc,jdbcType=VARCHAR}");
        }
        
        if (record.getNombre() != null) {
            VALUES("nombre", "#{nombre,jdbcType=VARCHAR}");
        }
        
        if (record.getSaldo() != null) {
            VALUES("saldo", "#{saldo,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public String selectByExample(ClienteExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id_cliente");
        } else {
            SELECT("id_cliente");
        }
        SELECT("ruc");
        SELECT("nombre");
        SELECT("saldo");
        FROM("cliente");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Cliente record = (Cliente) parameter.get("record");
        ClienteExample example = (ClienteExample) parameter.get("example");
        
        BEGIN();
        UPDATE("cliente");
        
        if (record.getIdCliente() != null) {
            SET("id_cliente = #{record.idCliente,jdbcType=INTEGER}");
        }
        
        if (record.getRuc() != null) {
            SET("ruc = #{record.ruc,jdbcType=VARCHAR}");
        }
        
        if (record.getNombre() != null) {
            SET("nombre = #{record.nombre,jdbcType=VARCHAR}");
        }
        
        if (record.getSaldo() != null) {
            SET("saldo = #{record.saldo,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("cliente");
        
        SET("id_cliente = #{record.idCliente,jdbcType=INTEGER}");
        SET("ruc = #{record.ruc,jdbcType=VARCHAR}");
        SET("nombre = #{record.nombre,jdbcType=VARCHAR}");
        SET("saldo = #{record.saldo,jdbcType=INTEGER}");
        
        ClienteExample example = (ClienteExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public String updateByPrimaryKeySelective(Cliente record) {
        BEGIN();
        UPDATE("cliente");
        
        if (record.getRuc() != null) {
            SET("ruc = #{ruc,jdbcType=VARCHAR}");
        }
        
        if (record.getNombre() != null) {
            SET("nombre = #{nombre,jdbcType=VARCHAR}");
        }
        
        if (record.getSaldo() != null) {
            SET("saldo = #{saldo,jdbcType=INTEGER}");
        }
        
        WHERE("id_cliente = #{idCliente,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tarea2.cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    protected void applyWhere(ClienteExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}