package py.pol.una.ii.pw.sqlprovider;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;

import py.pol.una.ii.pw.example.ProductoExample;
import py.pol.una.ii.pw.example.ProductoExample.Criteria;
import py.pol.una.ii.pw.example.ProductoExample.Criterion;
import py.pol.una.ii.pw.model.Producto;

public class ProductoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	public String countByExample(ProductoExample example) {
		BEGIN();
		SELECT("count(*)");
		FROM("producto");
		applyWhere(example, false);
		return SQL();
	}

	 /* This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	public String deleteByExample(ProductoExample example) {
		BEGIN();
		DELETE_FROM("producto");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	public String insertSelective(Producto record) {
		BEGIN();
		INSERT_INTO("producto");

		if (record.getIdProducto() != null) {
			VALUES("id_producto", "#{idProducto,jdbcType=INTEGER}");
		}

		if (record.getNombre() != null) {
			VALUES("nombre", "#{nombre,jdbcType=VARCHAR}");
		}

		if (record.getPrecio() != null) {
			VALUES("precio", "#{precio,jdbcType=INTEGER}");
		}

		if (record.getStock() != null) {
			VALUES("stock", "#{stock,jdbcType=INTEGER}");
		}

		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	public String selectByExample(ProductoExample example) {
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT("id_producto");
		} else {
			SELECT("id_producto");
		}
		SELECT("nombre");
		SELECT("precio");
		SELECT("stock");
		FROM("producto");
		applyWhere(example, false);

		if (example != null && example.getOrderByClause() != null) {
			ORDER_BY(example.getOrderByClause());
		}

		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Producto record = (Producto) parameter.get("record");
		ProductoExample example = (ProductoExample) parameter.get("example");

		BEGIN();
		UPDATE("producto");

		if (record.getIdProducto() != null) {
			SET("id_producto = #{record.idProducto,jdbcType=INTEGER}");
		}

		if (record.getNombre() != null) {
			SET("nombre = #{record.nombre,jdbcType=VARCHAR}");
		}

		if (record.getPrecio() != null) {
			SET("precio = #{record.precio,jdbcType=INTEGER}");
		}

		if (record.getStock() != null) {
			SET("stock = #{record.stock,jdbcType=INTEGER}");
		}

		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	public String updateByExample(Map<String, Object> parameter) {
		BEGIN();
		UPDATE("producto");

		SET("id_producto = #{record.idProducto,jdbcType=INTEGER}");
		SET("nombre = #{record.nombre,jdbcType=VARCHAR}");
		SET("precio = #{record.precio,jdbcType=INTEGER}");
		SET("stock = #{record.stock,jdbcType=INTEGER}");

		ProductoExample example = (ProductoExample) parameter.get("example");
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	public String updateByPrimaryKeySelective(Producto record) {
		BEGIN();
		UPDATE("producto");

		if (record.getNombre() != null) {
			SET("nombre = #{nombre,jdbcType=VARCHAR}");
		}

		if (record.getPrecio() != null) {
			SET("precio = #{precio,jdbcType=INTEGER}");
		}

		if (record.getStock() != null) {
			SET("stock = #{stock,jdbcType=INTEGER}");
		}

		WHERE("id_producto = #{idProducto,jdbcType=INTEGER}");

		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.producto
	 * 
	 * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
	 */
	protected void applyWhere(ProductoExample example,
			boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}

		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}

		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}

				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}

					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1,
									criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2,
									criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j,
										k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}

		if (sb.length() > 0) {
			WHERE(sb.toString());
		}
	}

	


}