package py.pol.una.ii.pw.model;

public class Cliente {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tarea2.cliente.id_cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    private Integer idCliente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tarea2.cliente.ruc
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    private String ruc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tarea2.cliente.nombre
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tarea2.cliente.saldo
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    private Integer saldo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tarea2.cliente.id_cliente
     *
     * @return the value of tarea2.cliente.id_cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tarea2.cliente.id_cliente
     *
     * @param idCliente the value for tarea2.cliente.id_cliente
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tarea2.cliente.ruc
     *
     * @return the value of tarea2.cliente.ruc
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public String getRuc() {
        return ruc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tarea2.cliente.ruc
     *
     * @param ruc the value for tarea2.cliente.ruc
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public void setRuc(String ruc) {
        this.ruc = ruc == null ? null : ruc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tarea2.cliente.nombre
     *
     * @return the value of tarea2.cliente.nombre
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tarea2.cliente.nombre
     *
     * @param nombre the value for tarea2.cliente.nombre
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tarea2.cliente.saldo
     *
     * @return the value of tarea2.cliente.saldo
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public Integer getSaldo() {
        return saldo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tarea2.cliente.saldo
     *
     * @param saldo the value for tarea2.cliente.saldo
     *
     * @mbggenerated Fri Apr 22 22:31:52 PYT 2016
     */
    public void setSaldo(Integer saldo) {
        this.saldo = saldo;
    }
}