package py.pol.una.ii.pw.model;

import java.util.Date;

public class Compra {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.compra.id_compra
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idCompra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.compra.id_proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idProveedor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.compra.fecha
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Date fecha;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.compra.id_compra
     *
     * @return the value of public.compra.id_compra
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdCompra() {
        return idCompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.compra.id_compra
     *
     * @param idCompra the value for public.compra.id_compra
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.compra.id_proveedor
     *
     * @return the value of public.compra.id_proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdProveedor() {
        return idProveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.compra.id_proveedor
     *
     * @param idProveedor the value for public.compra.id_proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.compra.fecha
     *
     * @return the value of public.compra.fecha
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.compra.fecha
     *
     * @param fecha the value for public.compra.fecha
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
}