package py.pol.una.ii.pw.model;

public class Detallecompra {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.compra_detalle.id_compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idCompraDetalle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.compra_detalle.id_compra
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idCompra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.compra_detalle.id_producto
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idProducto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.compra_detalle.cantidad
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer cantidad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.compra_detalle.id_compra_detalle
     *
     * @return the value of public.compra_detalle.id_compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdCompraDetalle() {
        return idCompraDetalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.compra_detalle.id_compra_detalle
     *
     * @param idCompraDetalle the value for public.compra_detalle.id_compra_detalle
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdCompraDetalle(Integer idCompraDetalle) {
        this.idCompraDetalle = idCompraDetalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.compra_detalle.id_compra
     *
     * @return the value of public.compra_detalle.id_compra
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdCompra() {
        return idCompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.compra_detalle.id_compra
     *
     * @param idCompra the value for public.compra_detalle.id_compra
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.compra_detalle.id_producto
     *
     * @return the value of public.compra_detalle.id_producto
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdProducto() {
        return idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.compra_detalle.id_producto
     *
     * @param idProducto the value for public.compra_detalle.id_producto
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.compra_detalle.cantidad
     *
     * @return the value of public.compra_detalle.cantidad
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.compra_detalle.cantidad
     *
     * @param cantidad the value for public.compra_detalle.cantidad
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
}