package py.pol.una.ii.pw.model;

import java.util.Date;

public class Pago {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pago.id_pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idPago;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pago.id_cliente
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idCliente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pago.fecha
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pago.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer pago;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pago.id_pago
     *
     * @return the value of public.pago.id_pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdPago() {
        return idPago;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pago.id_pago
     *
     * @param idPago the value for public.pago.id_pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pago.id_cliente
     *
     * @return the value of public.pago.id_cliente
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pago.id_cliente
     *
     * @param idCliente the value for public.pago.id_cliente
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pago.fecha
     *
     * @return the value of public.pago.fecha
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pago.fecha
     *
     * @param fecha the value for public.pago.fecha
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pago.pago
     *
     * @return the value of public.pago.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getPago() {
        return pago;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pago.pago
     *
     * @param pago the value for public.pago.pago
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setPago(Integer pago) {
        this.pago = pago;
    }
}