package py.pol.una.ii.pw.model;

public class Producto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.id_producto
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idProducto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.nombre
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.precio
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer precio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.stock
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.id_producto
     *
     * @return the value of public.producto.id_producto
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdProducto() {
        return idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.id_producto
     *
     * @param idProducto the value for public.producto.id_producto
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.nombre
     *
     * @return the value of public.producto.nombre
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.nombre
     *
     * @param nombre the value for public.producto.nombre
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.precio
     *
     * @return the value of public.producto.precio
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getPrecio() {
        return precio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.precio
     *
     * @param precio the value for public.producto.precio
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.stock
     *
     * @return the value of public.producto.stock
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.stock
     *
     * @param stock the value for public.producto.stock
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}