package py.pol.una.ii.pw.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

public class ProductoDuplicado {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto_duplicado.id_producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */

	private Integer idProductoDuplicado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto_duplicado.cantidad
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    private Integer cantidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto_duplicado.id_producto
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    private Integer idProducto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto_duplicado.id_producto_duplicado
     *
     * @return the value of public.producto_duplicado.id_producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    public Integer getIdProductoDuplicado() {
        return idProductoDuplicado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto_duplicado.id_producto_duplicado
     *
     * @param idProductoDuplicado the value for public.producto_duplicado.id_producto_duplicado
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    public void setIdProductoDuplicado(Integer idProductoDuplicado) {
        this.idProductoDuplicado = idProductoDuplicado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto_duplicado.cantidad
     *
     * @return the value of public.producto_duplicado.cantidad
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    public Integer getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto_duplicado.cantidad
     *
     * @param cantidad the value for public.producto_duplicado.cantidad
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto_duplicado.id_producto
     *
     * @return the value of public.producto_duplicado.id_producto
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    public Integer getIdProducto() {
        return idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto_duplicado.id_producto
     *
     * @param idProducto the value for public.producto_duplicado.id_producto
     *
     * @mbggenerated Sat Apr 23 22:12:30 PYT 2016
     */
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
}