package py.pol.una.ii.pw.model;

public class Proveedor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.proveedor.id_proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idProveedor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.proveedor.nombre
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.proveedor.id_proveedor
     *
     * @return the value of public.proveedor.id_proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdProveedor() {
        return idProveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.proveedor.id_proveedor
     *
     * @param idProveedor the value for public.proveedor.id_proveedor
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.proveedor.nombre
     *
     * @return the value of public.proveedor.nombre
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.proveedor.nombre
     *
     * @param nombre the value for public.proveedor.nombre
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }
}