package py.pol.una.ii.pw.model;

import java.util.Date;

public class Venta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.venta.id_venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idVenta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.venta.fecha
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.venta.id_cliente
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer idCliente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.venta.monto
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    private Integer monto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.venta.id_venta
     *
     * @return the value of public.venta.id_venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdVenta() {
        return idVenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.venta.id_venta
     *
     * @param idVenta the value for public.venta.id_venta
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.venta.fecha
     *
     * @return the value of public.venta.fecha
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.venta.fecha
     *
     * @param fecha the value for public.venta.fecha
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.venta.id_cliente
     *
     * @return the value of public.venta.id_cliente
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.venta.id_cliente
     *
     * @param idCliente the value for public.venta.id_cliente
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.venta.monto
     *
     * @return the value of public.venta.monto
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public Integer getMonto() {
        return monto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.venta.monto
     *
     * @param monto the value for public.venta.monto
     *
     * @mbggenerated Sat Apr 23 22:10:07 PYT 2016
     */
    public void setMonto(Integer monto) {
        this.monto = monto;
    }
}